version: "3.2"

services:
  etm-price-profile-adapter:
    build: .
    volumes:
      - .:/code
    command: ["gunicorn", "--reload", "tno.etm_price_profile_adapter.main:app", "-t 300", "-w 1", "-b :9201"]
    ports:
      - "9201:9201"
    env_file:
      - ".env.docker"
    networks:
      - mmvib-net

networks:
  mmvib-net:
    external:
      name: mmvib-net
